@startwbs
* La guerra d'independència contra el francès
** Criteris de mínims
*** Tractat de Fontainebleau (1807)
*** Conjura de l'escorial
*** Motí d'aranjuez (1808)
*** Abdicacions de Baiona (1808)
*** Aixecament popular del 2 de Maig (1808)
*** Afusellaments del 3 de Maig (1808)
** Etapes
*** Primera etapa de la guerra (Juny-Novembre 1808)
**** Aixecaments/Afusellaments
**** Primera revolució liberal + Primera derrota 
**** Eviament de presos a l'Illa de Cabrera
*** Segona etapa de la guerra (Novembre 1808 - Juliol 1812)
**** Guerrilles
**** Napoleó dirigeix la Grand Armée
**** Victòries napoleòniques a Ocaña i Uclés
**** Refugi de la Junta Central Suprema a Cadis
**** Creació de les Corts de Cadis + Constitució del 1812
*** Tercera etapa de la guerra (Juliol 1812 - Novembre 1813)
**** Retirada de la Grand Armée per fer front a Rússia
**** Derrota de Napoleó Rússia + Contraofensiva angloespanyola (Duc de Wellington)
**** Derrotes a Los Arapiles, Vitoria, etc...
**** Retorn al govern de Ferran VII (Tractat de Valençay - Desembre 1813)
** Conseqüències finals i conclusió
*** Gran nombre de morts, aturada del comerç amb Amèrica, abandonament del camp...
*** Exili d'intelectuals
*** Anul·lació de la Constitució del 1812 (1814)
*** Emancipació de les colònies americanes
*** Inici de l'edat contemporània (abdicacions de Baiona i imposicions liberals de Josep I)
@endwbs
