@startmindmap
* Regnat de Ferran VII
**:Introducció
- Tractat de Valençay (1813)
- Arribada al poder i recolzament de jovellanistes, il·lustrats i patriotes
;
**:Sexenni absolutista (1814-1820)
- Manifest dels perses + Derrota a la Guerra d'Independència
- Cop d'estat per abolir la constitució (1814)
- Conservació de certes colònies i emancipació
- Exiliats francesos degut a la repressió
- Fallida d'Hisenda
;
**: Trienni liberal (1820-1823)
- Pronunciament de Riego (1820)
- "Marchemos todos juntos, y yo el primero por la senda constitucional"
- Divisió de poders + Constitució del 1812
- Organitzció de Milícia Nacional
- Supressió de Mayorazgos, Desamortització de l'esglèsia, l'abolició de la Inquisició
- Divisió en dos governs --> Martinez de la Rosa (Pronunciaments) | Evaristo San Miguel (Cent Mil Fills de Sant Lluís + Santa Aliança)
;

**: Dècada ominosa (1823-1833)
- Repressió ferotge del liberalisme
- Reaplicació de les mesures prèvies al trienni liberal
- Sectors absolutistes passen a recolzar Carles Maria Isidre
- Reformes que no agraden a cap dels Sectors
;
**: Problemes i conclusions
- El problema succesori (La Llei Sàlica)
- Mort de Ferran VII
- Inici de la Primera Guerra Carlista (1833-1840)
;

@endmindmap